// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAMW6IWgJ0bmcNnuFWN5z2Sz3-gJn4Nt4',
    appId: '1:380106669327:web:3e531e29b55e7d51ee527a',
    messagingSenderId: '380106669327',
    projectId: 'lab7-67ed3',
    authDomain: 'lab7-67ed3.firebaseapp.com',
    storageBucket: 'lab7-67ed3.appspot.com',
    measurementId: 'G-S1QJQD455Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWU7UZg_Gn9-n2srbw3KzdakacaFkFd20',
    appId: '1:380106669327:android:a48e96196189054aee527a',
    messagingSenderId: '380106669327',
    projectId: 'lab7-67ed3',
    storageBucket: 'lab7-67ed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6S3WSbNB29E-7xQmyhdobJhCVrNgdN6U',
    appId: '1:380106669327:ios:e53365ceda49cbb4ee527a',
    messagingSenderId: '380106669327',
    projectId: 'lab7-67ed3',
    storageBucket: 'lab7-67ed3.appspot.com',
    iosBundleId: 'com.example.lab7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6S3WSbNB29E-7xQmyhdobJhCVrNgdN6U',
    appId: '1:380106669327:ios:7c323774e4be1e00ee527a',
    messagingSenderId: '380106669327',
    projectId: 'lab7-67ed3',
    storageBucket: 'lab7-67ed3.appspot.com',
    iosBundleId: 'com.example.lab7.RunnerTests',
  );
}
